### ISSUE TITLE
add a page of javascript learning resources

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICM-2015#1]
pull from networked media, a to z, etc.

**Comment by lmccart** [comment]
I started a page here: https://github.com/ITPNYU/ICM-2015/wiki/Resources

**Comment by lmccart** [comment]
moved resources to README, combined with existing resources section. closed with https://github.com/ITPNYU/ICM-2015/commit/b2a272dfaf5bb8882c839f7e2715dadd2425c964
