### ISSUE TITLE
Place for Email and Individual Office hours

### ISSUE THREAD

**Issue by vanevery** [ITPNYU/ICM-2015#12]
Should we just add those to the syllabus or on our individual homework wiki pages?

**Comment by shiffman** [comment]
Yes, we need this.  Last year, we had separate markdown pages in the repo for individual  section info.  What about just adding it all to https://github.com/ITPNYU/ICM-2015/blob/master/schedule.md and renaming it to something like "section specifics"?  I need to finalize the content for that page and link it from the syllabus as well.

**Comment by shiffman** [comment]
Updated this page for section info and scheduling.  Please edit and update as you wish!

https://github.com/ITPNYU/ICM-2015/blob/master/sections.md
