### ISSUE TITLE
Google Groups per section?

### ISSUE THREAD

**Issue by vanevery** [ITPNYU/ICM-2015#13]
Do we want to do this or is it too much to manage?

Will we need Rob to create per section?

**Comment by lmccart** [comment]
I think I will forego the section google group for my classes and just use the "list emails" link from the itp site when I need to email only my section. this way they won't have to decide between two diff lists when emailing code questions.

**Comment by vanevery** [comment]
I agree.  Will get too confusing.  I'm already confused enough.

**Comment by shiffman** [comment]
Code questions should only go to the main list.  The section list is totally unnecessary, I usually make a google group announce list myself for convenience (you don't need Rob to make an nyu.edu one, only an  itp.nyu.edu one), but using the ITP "list e-mails" is just as good.   Feel free to do whatever you prefer of course!
