### ISSUE TITLE
attendance policy

### ISSUE THREAD

**Issue by lmccart** [ITPNYU/ICM-2015#14]
sounds vague right now. would it be helpful to be more specific about what "excessive" means in writing? 
something like more than 2 absences results in fail, more than 10 mins late to a class = half an absence?

**Comment by shiffman** [comment]
Yes, agree!  I will add some language now and I think it might be better served integrated with #12.

**Comment by shiffman** [comment]
I changed the language on the main syllabus.  Please adjust as you see fit.
