### ISSUE TITLE
week 3 assignment

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICM-2015#18]
I'm thinking about the language for week 3 assignment.  Maybe it will come together in my head in class tomorrow.  This is something like what we had last year. . too much, too little?   Other ideas?

I can update the Processing references to be p5.js ones.

---

In general this week, you should work with rule-based animation, motion, and interaction.  You can use the ideas below or invent your own assignment.  Start by working in pairs according to the wiki.  Can you divide an idea into two parts and combine those parts?  Can you swap sketches and riff of of your partner's work? You can post together or break off and complete the assignment individually.
1. Try making a rollover, button, or slider from scratch.  Compare your code to the [examples on github](https://github.com/ITPNYU/ICM-2015/tree/master/03_interaction/GUI).  Later we'll look at how this compare to interface elements we'll get for free from the browser.
2. Create an algorithmic design with simple parameters.  (One example is [10PRINT](htt://10print.org/), [examples code](https://github.com/ITPNYU/ICM-2014/tree/master/exercises-inclass/week3-control/10print)). 
3. Tie the above two together and have an interface element control the visual design or behavior of other elements in your sketch.

**Comment by lmccart** [comment]
I like it! I wonder if "algorithmic design" plus the 10PRINT reference limits the ideas too much? but maybe limits are good.

**Comment by lmccart** [comment]
by the way, I'm working on porting the rest of those gui examples right now.
I put a bunch of things in week 3 last night, it's not comprehensive. feel free to rearrange, organize or number however you like.

**Comment by lmccart** [comment]
oh, just realized these are all from learning processing, so I guess you have already ported them. I won't duplicate the effort then. :)

**Comment by shiffman** [comment]
I think it would be best if it were more open-ended and included examples/references to more than just 10PRINT?  

The GUI ones aren't from Learning Processing (I don't think?) so go ahead if you have some of them already!   I was about to bring the LP examples over, but since there are so many good ones here already I thought I would not overwhelm the repo and just put a link on the syllabus to additional examples?

**Comment by lmccart** [comment]
ah ok i'll port them then

**Comment by shiffman** [comment]
Ok, you can see what I have here:

https://github.com/ITPNYU/ICM-2015/wiki/Homework-Shiffman-Tuesday#week-3

Improvements, ideas, welcome of course. . .

**Comment by rouxpz** [comment]
just want to add that in addition to what dan just sent, i also gave my students the additional option of making or recreating a simple game (i used pong as the example, but they are free to come up with their own), since a few of them were trying to do that _anyway_ for week 2's homework. here's my wiki for reference, let me know if you guys have any further ideas: https://github.com/ITPNYU/ICM-2015/wiki/Homework-Roopa-Tuesday#week-3
