### ISSUE TITLE
video examples

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICM-2015#20]
I added a few examples under week 9.  There are more at http://p5js.org that would be good to incorporate.  Some questions / other ideas:
- [x] Is the pixels array too much right now, should I stick with `get()`?
- [x] Consider a https://github.com/auduno/clmtrackr example.
- [x] I'd like to add a quick popcorn.js example to fire events in canvas at moments in a video.

What else?

**Comment by vanevery** [comment]
I think pixels[] is best as there are a ton of Processing examples that they could easily port that use it.
clmtrackr seems like a great idea.  Under the hood it uses 
Should we use the DOM library's addCue function instead of Popcorn?

**Comment by lmccart** [comment]
I recommend avoiding pixels as it is a bit complicated with the array that the pixels array is arranged in p5.js. http://p5js.org/reference/#p5.Image/pixels[]
We could put a couple in the repo though.
I can add that and an example for clmtrackr.

**Comment by lmccart** [comment]
ok just added examples for: video, video pixels, capture pixels (slitscan), clmtrackr, clmtrackr emotion

**Comment by shiffman** [comment]
Closing this for now as we have good examples thanks all!
