### ISSUE TITLE
where do tools come from?

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ICM-2015#4]
Does this go in week 1?  Week 14?

(from a different e-mail / comment thread)

> potential bonus topic could be talking a bit about where these tools came from. Open source, how artists make and adapt tools for themselves and their communities, like Processing, p5.js, openFrameworks, etc. How one might get involved with this.

**Comment by kylemcdonald** [comment]
wow, this is looking like it's going to be an amazing course!

**Comment by shiffman** [comment]
Now incorporated in the beginning (week 1) and the end (week 11)
